"""Planner agent for research query decomposition and search planning."""

from typing import Any

from pydantic import BaseModel, Field

from deep_research.agents.base import BaseAgent
from deep_research.core.exceptions import LLMProviderError
from deep_research.models.plan import ResearchPlan, SubQuestion
from deep_research.models.state import ResearchState, ResearchStatus, StepResult
from deep_research.providers.llm.base import BaseLLMProvider


class GeneratedSubQuestion(BaseModel):
    """Sub-question generated by LLM planner."""

    question_id: str = Field(description="Unique ID e.g. SQ-1, SQ-2")
    question: str = Field(description="Targeted orthogonal research question")
    rationale: str = Field(
        description="Why this sub-question is critical to answering the overall topic"
    )
    target_queries: list[str] = Field(
        description="2-3 specific search queries to address this question"
    )


class GeneratedResearchPlan(BaseModel):
    """Structured plan output generated by LLM."""

    primary_objective: str = Field(description="Core formulated research objective")
    hypotheses: list[str] = Field(default_factory=list, description="Key hypotheses to investigate")
    sub_questions: list[GeneratedSubQuestion] = Field(description="List of 3 to 5 sub-questions")
    initial_search_queries: list[str] = Field(
        description="Consolidated set of prioritized initial search queries"
    )


PLANNER_SYSTEM_INSTRUCTION = """You are a Principal Scientific Research Strategist.
Your mission is to analyze open-ended research questions and decompose them into an exhaustive, highly structured investigation plan.

PLANNING RULES:
1. Deconstruct the inquiry into 3-5 orthogonal, non-overlapping sub-questions.
2. For each sub-question, specify concrete search queries using effective search keywords and operators.
3. Avoid generic queries. Include specific terminology, metrics, technical standards, and domain entities.
4. Formulate testable hypotheses to investigate.
5. Prioritize search queries designed to find primary sources, academic literature, benchmarks, or official reports.
"""


class PlannerAgent(BaseAgent):
    """Decomposes research topics into structured hypotheses, sub-questions, and search queries."""

    def __init__(self, llm: BaseLLMProvider) -> None:
        super().__init__(agent_name="PlannerAgent", llm=llm)

    async def run(self, state: ResearchState, **kwargs: Any) -> StepResult:
        if not self.llm:
            raise LLMProviderError("PlannerAgent requires an active LLM provider.")

        state.transition_to(
            ResearchStatus.PLANNING, "Decomposing research query into structured plan"
        )

        prompt = (
            f"Research Topic: {state.initial_query}\n"
            f"Execution Mode: {state.mode.value}\n"
            f"Max Iterations Allowed: {state.max_iterations}\n\n"
            f"Develop a rigorous research blueprint decomposing this topic."
        )

        try:
            generated_plan, usage = await self.llm.generate_structured(
                prompt=prompt,
                response_model=GeneratedResearchPlan,
                system_instruction=PLANNER_SYSTEM_INSTRUCTION,
                temperature=0.2,
            )
            state.budget.record_llm_call(
                prompt_tokens=usage.prompt_tokens,
                completion_tokens=usage.completion_tokens,
                cost_usd=usage.cost_usd,
            )

            # Convert to domain ResearchPlan model
            sub_questions: list[SubQuestion] = [
                SubQuestion(
                    question_id=sq.question_id,
                    question=sq.question,
                    rationale=sq.rationale,
                    target_queries=sq.target_queries,
                )
                for sq in generated_plan.sub_questions
            ]

            # Aggregate initial search queries if not already present
            all_queries = list(generated_plan.initial_search_queries)
            for sq in sub_questions:
                for q in sq.target_queries:
                    if q not in all_queries:
                        all_queries.append(q)

            plan = ResearchPlan(
                primary_objective=generated_plan.primary_objective,
                hypotheses=generated_plan.hypotheses,
                sub_questions=sub_questions,
                initial_search_queries=all_queries,
                planned_mode=state.mode,
                max_iterations=state.max_iterations,
            )
            state.plan = plan

            summary = (
                f"Formulated research plan with {len(plan.sub_questions)} sub-questions "
                f"and {len(plan.initial_search_queries)} search queries"
            )
            return StepResult(
                agent_name=self.agent_name,
                status="completed",
                summary=summary,
                items_produced=len(plan.sub_questions),
            )

        except Exception as e:
            self.logger.warning("planner_structured_failed_falling_back", error=str(e))
            # Resilient fallback: construct deterministic heuristic plan
            fallback_plan = self._build_heuristic_plan(state)
            state.plan = fallback_plan
            return StepResult(
                agent_name=self.agent_name,
                status="completed_fallback",
                summary=f"Formulated heuristic plan with {len(fallback_plan.sub_questions)} sub-questions",
                items_produced=len(fallback_plan.sub_questions),
            )

    def _build_heuristic_plan(self, state: ResearchState) -> ResearchPlan:
        """Construct a deterministic baseline plan when LLM generation is unavailable."""
        q = state.initial_query
        sub_qs = [
            SubQuestion(
                question_id="SQ-1",
                question=f"What are the foundational principles and current state of {q}?",
                rationale="Establish technical baseline and terminology",
                target_queries=[f"{q} fundamentals overview", f"{q} state of the art"],
            ),
            SubQuestion(
                question_id="SQ-2",
                question=f"What are the key technical challenges, limitations, and competing approaches in {q}?",
                rationale="Identify bottlenecks and comparative trade-offs",
                target_queries=[f"{q} challenges limitations", f"{q} alternatives comparison"],
            ),
            SubQuestion(
                question_id="SQ-3",
                question=f"What are the recent breakthroughs, empirical results, and future outlook for {q}?",
                rationale="Synthesize latest developments and industry trajectory",
                target_queries=[
                    f"{q} latest breakthroughs 2025 2026",
                    f"{q} future trends roadmaps",
                ],
            ),
        ]
        all_queries = [query for sq in sub_qs for query in sq.target_queries]
        return ResearchPlan(
            primary_objective=q,
            hypotheses=[
                f"{q} represents a significant paradigm shift with active technical challenges."
            ],
            sub_questions=sub_qs,
            initial_search_queries=all_queries,
            planned_mode=state.mode,
            max_iterations=state.max_iterations,
        )
