"""Cost tracking and token budget management models."""

from pydantic import BaseModel, Field


class TokenUsage(BaseModel):
    """Token accounting for individual LLM requests."""

    prompt_tokens: int = Field(ge=0, default=0, description="Input tokens sent to LLM")
    completion_tokens: int = Field(ge=0, default=0, description="Output tokens generated by LLM")
    cost_usd: float = Field(ge=0.0, default=0.0, description="Calculated dollar cost of call")

    @property
    def total_tokens(self) -> int:
        """Total tokens across prompt and completion."""
        return self.prompt_tokens + self.completion_tokens


class BudgetTracker(BaseModel):
    """Tracks cumulative expenditure and enforces cost ceilings."""

    max_budget_usd: float = Field(gt=0.0, description="Hard budget ceiling in USD")
    current_cost_usd: float = Field(ge=0.0, default=0.0, description="Cumulative cost accrued")
    prompt_tokens: int = Field(ge=0, default=0, description="Total prompt tokens consumed")
    completion_tokens: int = Field(ge=0, default=0, description="Total completion tokens consumed")
    search_api_calls: int = Field(
        ge=0, default=0, description="Number of search queries dispatched"
    )
    search_cost_usd: float = Field(ge=0.0, default=0.0, description="Cumulative search API spend")

    @property
    def is_exceeded(self) -> bool:
        """Returns True if expenditure has reached or exceeded the ceiling."""
        return self.current_cost_usd >= self.max_budget_usd

    @property
    def remaining_budget_usd(self) -> float:
        """Remaining funds before hard ceiling is reached."""
        return round(max(0.0, self.max_budget_usd - self.current_cost_usd), 6)

    def record_llm_call(self, prompt_tokens: int, completion_tokens: int, cost_usd: float) -> None:
        """Record an LLM call's token consumption and financial cost."""
        self.prompt_tokens += prompt_tokens
        self.completion_tokens += completion_tokens
        self.current_cost_usd = round(self.current_cost_usd + cost_usd, 6)

    def record_search_call(self, cost_usd: float = 0.0) -> None:
        """Record a search API call and increment search spend."""
        self.search_api_calls += 1
        self.search_cost_usd = round(self.search_cost_usd + cost_usd, 6)
        self.current_cost_usd = round(self.current_cost_usd + cost_usd, 6)
